# Python Numpy Array



## Numpy--
NumPy is a general purpose array processing package. It peovide a high perfomace multidimesional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

## What is an array --
An array is a data structure that stores values of some data type. In Python, this is the main difference between array and lists. while python lists can contain values corresponding to different data types, array in python can only contain values corresponding to same data type.


In [2]:
## import the numpy 

import numpy as np

In [9]:
 ## one dimional array 
ls=[1,23,4,5,]
arr= np.array(ls)
print(arr)

[ 1 23  4  5]


In [10]:
type(arr)

numpy.ndarray

In [20]:
## two diminal array 
ls1=[1,2,3,4,5]
ls2=[6,7,8,9,0]
ls3=[11,12,13,14,15]

arr1=np.array([ls1,ls2,ls3])

In [12]:
arr

array([ 1, 23,  4,  5])

In [13]:
# indexing 

arr[2]

4

In [14]:
## change the element by indexing

arr[1]=2

In [15]:
arr

array([1, 2, 4, 5])

In [16]:
#split the array 


arr[1:]

array([2, 4, 5])

In [17]:
arr[2:4]

array([4, 5])

In [18]:
# to display the last element 
arr[-1]

5

In [19]:
## to reverse the array 

arr[::-1]

array([5, 4, 2, 1])

In [21]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [22]:
arr1[:,:1]

array([[ 1],
       [ 6],
       [11]])

In [23]:
arr1[1:,:2]

array([[ 6,  7],
       [11, 12]])

In [24]:
arr1[1:,2:]

array([[ 8,  9,  0],
       [13, 14, 15]])

In [25]:
arr1[1:,3:]

array([[ 9,  0],
       [14, 15]])

In [26]:
arr1[:,3:]

array([[ 4,  5],
       [ 9,  0],
       [14, 15]])

In [27]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [33]:
arr1[:0,:4]

array([], shape=(0, 4), dtype=int32)

In [34]:
## EDA

arr

array([1, 2, 4, 5])

In [35]:
arr<2

array([ True, False, False, False])

In [36]:
## finding the the element is true by the condition 
arr[arr<2]

array([1])

In [38]:
## mechanism to create an arry

np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
## reshape 
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
## Multiplcation of array 

arr1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0],
       [22, 24, 26, 28, 30]])

In [47]:
arr1*arr1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81,   0],
       [121, 144, 169, 196, 225]])