## Tutorial-8  Python Pnads Tutorials- part- 1

In the part we are going to learn about

1. Pandas Dataframe
2. Pandas series
3. Pandas Basic Operations 

In [1]:
import pandas as pd
import numpy as np

## Dataframe

In [4]:
# to creating an array
data=np.arange(0,20).reshape(5,4)

In [5]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
#gettting the data from the array and puting the index name
df=pd.DataFrame(data,index=["1","2","3","4","5"],columns=["1","2","3","4"])

In [24]:
df.head()

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [25]:
df.tail()

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

### this is called the data frame

In [26]:
# to find the data type
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       5 non-null      int32
 1   2       5 non-null      int32
 2   3       5 non-null      int32
 3   4       5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [27]:
# to find the statistical value
df.describe()

1          2          3          4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [28]:
df.head()

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [31]:
# getting the details of perticular column or row by indexing
df[["1","2","3"]]

1   2   3
1   0   1   2
2   4   5   6
3   8   9  10
4  12  13  14
5  16  17  18

In [32]:
# row by indexing
df.loc["3"]

1     8
2     9
3    10
4    11
Name: 3, dtype: int32

In [33]:
df.loc[["2","3"]]

1  2   3   4
2  4  5   6   7
3  8  9  10  11

In [34]:
df

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [35]:
df.iloc[2:4,1:3]

2   3
3   9  10
4  13  14

## loc is primarily used for label indexing, and the . iloc function is mainly used for integer indexing

In [36]:
df

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [40]:
df.iloc[:,[0,3]]

1   4
1   0   3
2   4   7
3   8  11
4  12  15
5  16  19

In [47]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Basic operation

In [48]:
df

1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [49]:
# check the null values

df.isnull()

1      2      3      4
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False

In [50]:
df["3"].value_counts()

3
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [52]:
df["3"].unique()

array([ 2,  6, 10, 14, 18])

In [53]:
df["2"]>2

1    False
2     True
3     True
4     True
5     True
Name: 2, dtype: bool